### ISSUE TITLE
partial sources in source method

### ISSUE THREAD

**Issue by ericLemanissier** [osechet/conan-qt#36]
Doing some tests, it seems like it is wrong to get only partial sources in the build method : when calling conan create on a package requiring Qt, even with "-b Qt" it reuses the existing sources in the local cache, disregarding the options used, so modules disabled the first time the source method was called cannot be added later.
Probably the correct option is to get all the submodules sources in the source method, an then build only the ones selected in the build method. The recommended way to get the full sources is to get  qt-everywhere-opensource-src-5.8.0.tar.xz archive (354MB)

**Comment by vadixidav** [comment]
This is still an issue today. This is an issue for me as well. I agree with @ericLemanissier that we should use the archive, as its download is a lot faster than even a few git repositories. We also don't want to do shallow clones of Qt because that allegedly (from what GitHub says) puts quite a load on GitHub servers.
